twitter/urls.py
from django.conf.urls import include, url
from . import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^$', views.MainView.as_view(), name='welcome'),
    url(r'^signup/',views.AuthorSignUpView.as_view(), name='signup'),
    url(r'^login/',views.AuthorLoginView.as_view(), name='login'),
    url(r'^logout/',views.AuthorLogoutView.as_view(), name='logout'),
    url(r'^@(?P<nickname>[^/]+)/$', views.AuthorTweetsView.as_view(), name='tweets'),
    url(r'^@(?P<nickname>[^/]+)/(?P<slug>[^/]+)/$', views.TweetView.as_view(), name='tweet_by_slug'),
    url(r'^submitpost/', views.TweetCreateView.as_view(), name='submit_post'),
    url(r'^tag/(?P<tag>[^/]+)/$', views.TagView.as_view(), name='tag_list'),
    url(r'^feed/$', views.FeedView.as_view(), name='feed'),
    url(r'^tweet/(?P<tweet_id>\d+)/like/$', views.AddLikeView.as_view(), name='add_like'),
    url(r'^tweet/(?P<tweet_id>\d+)/unlike/$', views.RemoveLikeView.as_view(), name='remove_like'),
    url(r'^(?P<author_id>\d+)/follow/$', views.FollowView.as_view(), name='follow'),
    url(r'^(?P<author_id>\d+)/unfollow/$', views.UnfollowView.as_view(), name='unfollow'),
    url(r'^tweet/(?P<tweet_id>\d+)/repost/$', views.RepostView.as_view(), name='repost'),
    url(r'^tweet/(?P<tweet_id>\d+)/delete/$', views.DeletePostView.as_view(), name='delete_post'),
    url(r'^tweet/(?P<tweet_id>\d+)/(?P<comment_id>\d+)/delete/$', views.DeleteCommentView.as_view(), name='delete_comment'),
    url(r'^notifications/$', views.NotificationsView.as_view(), name='notifications'),
    url(r'^testpage/$', views.TestPageView.as_view(), name='testpage'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

twitter/models.py
import datetime
from django.utils import timezone
from django.db import models
from django.core.urlresolvers import reverse
from hashlib import md5



def generate_imagename(self, imgname):
    ext = imgname.split('.')[-1]
    url = "photo.%s" % (ext)
    return url


def generate_photoname(self, imgname):
    ext = imgname.split('.')[-1]
    url = "%s/photo.%s" % (self.nickname, ext)
    return url


class Commentary(models.Model):
    tweet = models.ForeignKey('Tweet')
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey('registration.Author')
    comment = models.CharField(max_length=170)

    def __str__(self):
        return self.comment


class Tweet(models.Model):
    tweet_text = models.CharField(max_length=170)
    likes = models.ManyToManyField('registration.Author', verbose_name='падабайкi', related_name='favourite_tweets', blank=True)
    pub_date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to=generate_imagename, blank=True)
    slug = models.SlugField(unique=True, help_text="Вычисляется автоматически")
    author = models.ForeignKey('registration.Author')
    reposted_from=models.ForeignKey('self', blank=True, null=True)

    class Meta:
        ordering = ["-pub_date"]

    def save(self, *args, **kwargs):
        if not self.id and not self.slug:
            super(Tweet, self).save(*args, **kwargs)
            current_time = str(datetime.datetime.now().time())
            self.slug = md5(str(str(self.id)+current_time).encode('utf-8')).hexdigest()[:20]
        super(Tweet, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('tweet_by_slug', kwargs={'nickname': self.author.nickname, 'slug': self.slug})

    def get_image_url(self):
        if self.image:
            return self.image.url

    def __str__(self):
        return self.slug


class Author(models.Model):
    name = models.CharField(max_length=50)
    nickname = models.SlugField(unique=True)
    email = models.EmailField(blank=True, unique=True)
    photo = models.ImageField(upload_to=generate_photoname, blank=True)

    def get_absolute_url(self):
        return reverse('tweets', kwargs={'nickname': self.nickname})

    def __str__(self):
        return self.name


class Event(models.Model):
    TYPE_CHOICES = (
        ('like', 'лайк'),
        ('repost', 'репост'),
        ('comment', 'коммент'),
        ('follow', 'подписка'),
        ('unfollow', 'отписка'),
    )
    from_who = models.ForeignKey('registration.Author', verbose_name='Event initiator', related_name='event_initiator', db_index=True)
    to_who = models.ForeignKey('registration.Author', verbose_name='Event target', related_name='event_target',  db_index=True)
    tweet = models.ForeignKey('Tweet', verbose_name='Related tweet', related_name='event_tweet', null=True, blank=True)
    event_type = models.CharField(choices=TYPE_CHOICES, max_length=100)
    datetime = models.DateTimeField(auto_now_add=True)

twitter/forms.py
from django import forms
from .models import Commentary, Tweet
from registration.models import Author


'''class AuthorSignUpForm(ModelForm):
    class Meta:
        model = Author
        fields = ["name", "nickname", "email", "photo",] '''


class AuthorSignUpForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Password',}))
    password_repeat = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Password repeat',}))

    class Meta:
        model = Author
        fields = ['name', 'nickname', 'email', 'photo']
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Name', 'maxlength': 200}),
            'email': forms.TextInput(attrs={'placeholder': 'E-mail', 'maxlength': 100}),
            'nickname': forms.TextInput(attrs={'placeholder': 'Nickname', 'maxlength': 20}),
            'photo': forms.ClearableFileInput(attrs={'placeholder': 'Photo',}),
        }

    def clean_password_repeat(self):
        password = self.cleaned_data.get('password')
        password_repeat = self.cleaned_data.get('password_repeat')

        if password and password_repeat and password != password_repeat:
            raise forms.ValidationError('Пароли не совпадают')

        return password_repeat

    def save(self, commit=True):
        author = super(AuthorSignUpForm, self).save(commit=False)
        author.set_password(self.cleaned_data['password'])

        if commit:
            author.save()

        return author


class AuthorLoginForm(forms.Form):
    email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder':'E-mail',}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Password',}))

    def clean(self):
        cleaned_data = super(AuthorLoginForm, self).clean()
        if not self._errors:
            email = cleaned_data.get('email')
            password = cleaned_data.get('password')
            try:
                author = Author.objects.get(email=email)
                if not author.check_password(password):
                    raise forms.ValidationError('wrong')
                elif author.is_blocked:
                    raise forms.ValidationError('blocked')
            except Author.DoesNotExist:
                raise forms.ValidationError('wrong')
        return cleaned_data


class TweetCommentsForm(forms.ModelForm):
    class Meta:
        model = Commentary
        fields = ["comment", "author", "tweet",]


class TweetCreateForm(forms.ModelForm):
    class Meta:
        model = Tweet
        fields = ["tweet_text", "author", "image",]


class TweetRepostForm(forms.ModelForm):
    class Meta:
        model = Tweet
        fields = ["reposted_from"]

twitter/views.py
from django.shortcuts import get_object_or_404, render
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from .models import Commentary, Tweet, Event
from registration.models import Author
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login, logout
from .forms import AuthorSignUpForm, TweetCommentsForm, TweetCreateForm, AuthorLoginForm
from django.http import JsonResponse
from django.db import IntegrityError
from django.template.loader import get_template
from django.template import Context
from hashlib import md5


class MainView(generic.TemplateView):
    template_name = "twitter/main.html"


class AuthorSignUpView(generic.CreateView):
    model = Author
    form_class = AuthorSignUpForm
    template_name = "twitter/signup.html"

    def get_success_url(self):
        return reverse('welcome')

    def form_valid(self, form):
        form.save()
        author = authenticate(**{'email': form.cleaned_data['email'], 'password': form.cleaned_data['password']})
        author.backend = 'django.contrib.auth.backends.ModelBackend'
        login(self.request, author)
        return super(AuthorSignUpView, self).form_valid(form)


class AuthorLoginView(generic.FormView):
    form_class = AuthorLoginForm
    template_name = "twitter/login.html"

    def get_success_url(self):
        return reverse('feed')

    def form_valid(self, form):
        author = authenticate(**form.cleaned_data)
        if author:
            login(self.request, author)
        return super(AuthorLoginView, self).form_valid(form)


class AuthorLogoutView(generic.View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return HttpResponseRedirect(redirect_to=reverse('welcome'))


class AuthorTweetsView(generic.CreateView):
    model = Commentary
    form_class = TweetCommentsForm
    template_name = "twitter/tweets.html"

    def get_context_data(self, **kwargs):
        context = super(AuthorTweetsView, self).get_context_data(**kwargs)
        context['author'] = get_object_or_404(Author, nickname=self.kwargs['nickname'])
        return context

    def get_success_url(self):
        return self.request.path

    def form_invalid(self, form):
        errors = []
        for k in form.errors:
            errors.append({'name': k, 'error': form.errors[k][0]})
        data = {'errors': errors, 'result': 'error'}
        return JsonResponse(data)

    def form_valid(self, form):
        form.save()
        return JsonResponse({'result': 'ok'})


class TweetCreateView(generic.CreateView):
    model = Tweet
    form_class = TweetCreateForm
    template_name = "twitter/tweets.html"

    def get_context_data(self, **kwargs):
        context = super(TweetCreateView, self).get_context_data(**kwargs)
        context['author'] = get_object_or_404(Author, nickname=self.kwargs['nickname'])
        tweet_was_reposted = self.request.user.tweet_set.all().values_list('reposted_from', flat=True)
        context['tweet_was_reposted'] = tweet_was_reposted
        return context

    def get_success_url(self):
        return self.request.path

    def form_invalid(self, form):
        errors = []
        for k in form.errors:
            errors.append({'name': k, 'error': form.errors[k][0]})
        data = {'errors': errors, 'result': 'error'}
        return JsonResponse(data)

    def form_valid(self, form, *args, **kwargs):
        super(TweetCreateView, self).form_valid(form, *args, **kwargs)
        template = get_template('twitter/js-post_ext.html')
        html = template.render(Context({'tweet':form.instance}))
        return JsonResponse({'result': 'ok', 'html':html})

class TweetView(generic.CreateView):
    model = Tweet
    form_class = TweetCommentsForm
    template_name = "twitter/tweet.html"

    def get_context_data(self, **kwargs):
        context = super(TweetView, self).get_context_data(**kwargs)
        context['tweet'] = get_object_or_404(Tweet, slug=self.kwargs['slug'])
        return context

    def get_success_url(self):
        return self.request.path

    def form_invalid(self, form):
        errors = []
        for k in form.errors:
            errors.append({'name': k, 'error': form.errors[k][0]})
        data = {'errors': errors, 'result': 'error'}
        return JsonResponse(data)

    def form_valid(self, form):
        form.save()
        return JsonResponse({'result': 'ok'})


class TagView(generic.ListView):
    model = Tweet
    context_object_name = 'tag_set'
    template_name = "twitter/tags.html"

    def get_queryset(self):
        tag = self.kwargs['tag']
        tag_set = Tweet.objects.filter(tweet_text__icontains="#{0}".format(tag))
        return tag_set.order_by('-pub_date')


class FeedView(LoginRequiredMixin, generic.ListView):
    model = Tweet
    context_object_name = 'tweet_set'
    template_name = "twitter/feed.html"
    login_url = '/login/'
    redirect_field_name = '/main/'

    def get_queryset(self):
        author = self.request.user
        queryset_1 = Tweet.objects.filter(author__in=author.follow.all())
        queryset_2 = author.tweet_set.all()
        tweet_set = queryset_1 | queryset_2
        return tweet_set.order_by('-pub_date')

    def get_context_data(self, **kwargs):
        context = super(FeedView, self).get_context_data(**kwargs)
        context['author'] = get_object_or_404(Author, id=self.request.user.id)
        return context


class AddLikeView(generic.View):

    def post(self, request, *args, **kwargs):
        try:
            tweet_id = kwargs['tweet_id']
            tweet = Tweet.objects.get(id=tweet_id)
            author = request.user
            tweet.likes.add(author)
            Event.objects.create(
                from_who = author,
                to_who = tweet.author,
                tweet = tweet,
                event_type = "like",
            )
            return JsonResponse({'result': 'ok', 'count': tweet.likes.count()})
        except (ValueError, KeyError, Tweet.DoesNotExist) as e:
            return JsonResponse({'result': 'error'})


class RemoveLikeView(generic.View):

    def post(self, request, *args, **kwargs):
        try:
            tweet_id = kwargs['tweet_id']
            tweet = Tweet.objects.get(id=tweet_id)
            author = request.user
            event = Event.objects.filter(from_who=author, tweet=tweet, event_type="like")
            event.delete()
            tweet.likes.remove(author)
            return JsonResponse({'result': 'ok', 'count': tweet.likes.count()})
        except (ValueError, KeyError, Tweet.DoesNotExist) as e:
            return JsonResponse({'result': 'error'})


class FollowView(generic.View):

    def post(self, request, *args, **kwargs):
        try:
            author_id = kwargs['author_id']
            author = Author.objects.get(id=author_id)
            follower = request.user
            follower.follow.add(author)
            Event.objects.create(
                from_who = follower,
                to_who = author,
                event_type = "follow",
            )
            return JsonResponse({'result': 'ok'})
        except (ValueError, KeyError, Tweet.DoesNotExist) as e:
            return JsonResponse({'result': 'error'})


class UnfollowView(generic.View):

    def post(self, request, *args, **kwargs):
        try:
            author_id = kwargs['author_id']
            author = Author.objects.get(id=author_id)
            follower = request.user
            follower.follow.remove(author)
            Event.objects.create(
                from_who = follower,
                to_who = author,
                event_type = "unfollow",
            )
            return JsonResponse({'result': 'ok'})
        except (ValueError, KeyError, Tweet.DoesNotExist) as e:
            return JsonResponse({'result': 'error'})


class RepostView(generic.View):

    def post(self, request, *args, **kwargs):
        try:
            tweet_id = kwargs['tweet_id']
            tweet = Tweet.objects.get(id=tweet_id)
            if self.request.user != tweet.author:
                Tweet.objects.create(
                    author = self.request.user,
                    reposted_from = tweet,
                    tweet_text = tweet.tweet_text,
                    image = tweet.image if tweet.image else None,
                    slug = str(tweet.slug)+str(self.request.user.id),
                )
                Event.objects.create(
                    from_who = self.request.user,
                    to_who = tweet.author,
                    tweet = tweet,
                    event_type = "repost",
                )
            return JsonResponse({'result': 'ok'})
        except (ValueError, KeyError, Tweet.DoesNotExist, IntegrityError) as e:
            return JsonResponse({'result': e})


class DeletePostView(generic.View):

    def post(self, request, *args, **kwargs):
        try:
            tweet_id = kwargs['tweet_id']
            tweet = Tweet.objects.get(id=tweet_id)
            author = tweet.author
            if self.request.user == author:
                tweet.delete()
            return JsonResponse({'result': 'ok'})
        except (ValueError, KeyError, Tweet.DoesNotExist) as e:
            return JsonResponse({'result': e})


class DeleteCommentView(generic.View):

    def post(self, request, *args, **kwargs):
        try:
            comment_id = kwargs['comment_id']
            tweet_id = kwargs['tweet_id']
            comment = Commentary.objects.get(id=comment_id)
            author = Tweet.objects.get(id=tweet_id).author
            if self.request.user == author:
                comment.delete()
            return JsonResponse({'result':'ok'})
        except (ValueError, KeyError, Commentary.DoesNotExist) as e:
            return JsonResponse({'result': e})


class NotificationsView(generic.ListView):
    model = Event

twitter/templates/twitter/acceptor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>

twitter/templates/twitter/feed.html
{% extends 'twitter/base.html' %}

{% block title %}
    <title>Feed</title>
{% endblock %}


{% block leftblock %}
    <div class="leftcolumn" style="border-radius: 0px 0px 30px 30px;">
        <a href="/feed"><h5>Your feed</h5></a>
        <a href="/notifications"><h5>Your notifications</h5></a>
        <a href="{% url "tweets" request.user.nickname %}"><h5>Your page</h5></a>
    </div>
{% endblock %}

{% block tweet_set %}
    {% for tweet in tweet_set %}
        <span class="tweet_wrap">
            {% if tweet.reposted_from != None %}
                <div class="reposted_tweet">
                    <h6 style="text-align: left; background-color:#223634; border:15px solid #223634; "><a href='/@{{ tweet.reposted_from.author.name }}'> <span class="bigger">⤷</span><strong> {{ tweet.reposted_from.author.name }}</a></strong> @{{ tweet.reposted_from.author.nickname }}</h6>
                    <p class="tweet_date"><a href='{{ tweet.reposted_from.get_absolute_url }}'>{{ tweet.reposted_from.pub_date|date:"d M" }}</a>{% if request.user == author %}<span class="js-delete_post" data-delete-url="{% url "delete_post" tweet.id %}"><a href="#">✖</a></span>{% endif %}</p>
                    <h4 class="tweet_text">{{ tweet.reposted_from.tweet_text }}</h4>
                    <p class="tweet_image">{% if tweet.reposted_from.image %}<img src="{{ tweet.reposted_from.image.url }}"/>{% endif %}</p>
            {% else %}
                <div class="tweet">
                    <h6 style="text-align: justify; word-spacing:20px;"><strong><a href='/@{{ tweet.author.name }}'>{{ tweet.author.name }}</a></strong> @{{ tweet.author.nickname }}</h6>
                    <p class="tweet_date"><a href='{{ tweet.get_absolute_url }}'>{{ tweet.pub_date|date:"d M" }}</a>{% if request.user == author %}<span class="js-delete_post" data-delete-url="{% url "delete_post" tweet.id %}"><a href="#">✖</a></span>{% endif %}</p>
                    <h4 class="tweet_text">{{ tweet.tweet_text }}</h4>
                    <p class="tweet_image">{% if tweet.image %}<img src="{{ tweet.image.url }}"/>{% endif %}</p>
            {% endif %}
            <div style="display:inline-flex; flex:auto;">
                <p class="tweet_repost"><a href="#" class="js-repost_button" data-repost-url="{% url 'repost' tweet.id %}">↪</a></p>
                <p class="tweet_likes"><a href="#" class="like_button{% if request.user in tweet.likes.all %} already_liked{% endif %}" data-like-url="{% url 'add_like' tweet.id %}" data-dislike-url="{% url 'remove_like' tweet.id %}"><span class='like_counter'>{{ tweet.likes.count }}</span><span class="bigger"> ♥ </span></a></p>
            </div>
            <div class="comment_list">
                <p style="margin-top:-20px;">{% for comment in tweet.commentary_set.all %}</p>
                    <p style="text-align: left;" class="commentary"> <a href="/@{{ comment.author.nickname }}">
                        <img style="height: 30px; border-radius:5px; margin: 0px 5px -10px 5px;" src='{{ comment.author.photo_url }}'></a>
                        {{ comment }} {{ comment.pub_date|date:"H:i, d.M" }} {% if tweet.author == request.user %}<span class="js-delete_comment" data-delete-comment-url="{% url "delete_comment" tweet.id comment.id %}"><a href="#">✖</a></span>{% endif %}</p>
                {% endfor %}
            </div>
            </div>

            {% if request.user.is_authenticated %}
                <div class="comment_form">
                    <form class="js-submit_comment" method="post" action="{{request.path}}" enctype="multipart/form-data" data-comment-author-photo-url="{{ request.user.photo_url }}" data-comment-author-nickname="{{ request.user.nickname }}">
                        {% csrf_token %}
                        <input type='hidden' name='author' value='{{ request.user.id }}' />
                        <input type='hidden' name='tweet' value='{{ tweet.id }}' />
                        <input class="text_field" maxlength="170" name="comment" type="text" />
                        <input class="submit_button" type="submit" value="▶" />
                    </form>
                </div>
                </span>
            {% endif %}
    {% endfor %}
{% endblock %}

twitter/templates/twitter/js-post_ext.html
<span class="tweet_wrap">
    <div class='tweet'>
        <h6 style="text-align: justify; word-spacing:20px;"><strong><a href='/@{{ tweet.author.name }}'>{{ tweet.author.name }}</a></strong> @{{ tweet.author.nickname }}</h6>
        <p class="tweet_date"><a href='{{ tweet.get_absolute_url }}'>{{ tweet.pub_date|date:"d M" }}</a><span class="js-delete_post" data-delete-url="{% url "delete_post" tweet.id %}"><a href="#">✖</a></span></p>
        <h4 class="tweet_text">{{ tweet.tweet_text }}</h4>
        <p class="tweet_image">{% if tweet.image %}<img src="{{ tweet.image.url }}"/>{% endif %}</p>
        <div style="display:inline-flex; flex:auto;">
            <p class="tweet_repost"><a href="#" class="js-repost_button" data-repost-url="{% url 'repost' tweet.id %}">↪</a></p>
            <p class="tweet_likes"><a href="#" class="like_button{% if request.user in tweet.likes.all %} already_liked{% endif %}" data-like-url="{% url 'add_like' tweet.id %}" data-dislike-url="{% url 'remove_like' tweet.id %}"><span class='like_counter'>{{ tweet.likes.count }}</span><span class="bigger"> ♥ </span></a></p>
        </div>
        <div class="comment_list">
            <p style="margin-top:-20px;">{% for comment in tweet.commentary_set.all %}</p>
            <p style="text-align: left;" class="commentary"> <a href="/@{{ comment.author.nickname }}">
                        <img style="height: 30px; border-radius:5px; margin: 0px 5px -10px 5px;" src='{{ comment.author.photo_url }}'></a>
                        {{ comment }} {{ comment.pub_date|date:"H:i, d.M" }} {% if tweet.author == request.user %}<span class="js-delete_comment" data-delete-comment-url="{% url "delete_comment" tweet.id comment.id %}"><a href="#">✖</a></span>{% endif %}</p>
                {% endfor %}
        </div>

    </div>


    <div class='comment_form'>
        <form class='js-submit_comment' method='post' action='/%40{{ tweet.author.nickname }}/' enctype='multipart/form-data' data-comment-author-photo-url='{{ tweet.author.photo_url }}' data-comment-author-nickname='{{ tweet.author.nickname }}'>
            {% csrf_token %}
            <input type='hidden' name='author' value='{{ tweet.author.id }}' />
            <input type='hidden' name='tweet' value='{{ tweet.id }}' />
            <input class='text_field' maxlength='170' name='comment' type='text' />
            <input class='submit_button' type='submit' value='▶' />
        </form>
    </div>
</span>

twitter/templates/twitter/login.html
<!DOCTYPE html>
{% load staticfiles %}


<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'twitter/style.css' %}" />
    <link rel="icon" type="image/png" href="http://www.favicon-generator.org/favicon-generator/htdocs/favicons/2015-11-05/d2638317c185659c4e458da1129d217e.ico"/>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
    <form method="post" action="{{request.path}}" enctype="multipart/form-data" id="signupform">
            {% csrf_token %}
            {{ request.user.is_anonymous }}
            {{ form.as_p }}
            <p><input type="submit" value="Send">
               <input type="reset" value="Reset"></p>
    </form>

    <h6 style="text-align:center; margin-top: 180px;"><a href="/">back to main</a></h6>
</body>
</html>

twitter/templates/twitter/notifications.html
{% extends 'twitter/base.html' %}

{% block title %}
    <title>{{ request.user }}'s notifications</title>
{% endblock %}

{% block leftblock %}
    <div class="leftcolumn" style="border-radius: 0px 0px 30px 30px;">
        <a href="/feed"><h5>Your feed</h5></a>
        <a href="/notifications"><h5>Your notifications</h5></a>
        <a href="{% url "tweets" request.user.nickname %}"><h5>Your page</h5></a>
    </div>
{% endblock %}

{% block tweet_set %}
    {% for event in event_set.all %}
        <div class="tweet">
            {% if event.get_event_type_display == "лайк" %}
                <a href="{% url 'tweets' event.from_who.nickname %}"><img style="height: 30px; border-radius:5px; margin: 0px 5px -10px 5px;" src="{{ event.from_who.photo_url }}"/>
                <span class="tweet_text">{{ event.from_who.nickname }}</a> {{ event.event_type }}d your tweet <a href="{% url 'tweet_by_slug' request.user.nickname event.tweet.slug %}"><strong>«{{ event.tweet.tweet_text }}»</strong></a></span>
                <span class="tweet_date">{{ event.datetime|date:"d M H:i" }}</span>
            {% elif event.get_event_type_display == "репост" %}
                <a href="{% url 'tweets' event.from_who.nickname %}"><img style="height: 30px; border-radius:5px; margin: 0px 5px -10px 5px;" src="{{ event.from_who.photo_url }}"/>
                <span class="tweet_text">{{ event.from_who.nickname }}</a> {{ event.event_type }}ed your tweet <a href="{% url 'tweet_by_slug' event.from_who.nickname event.tweet.slug %}"><strong>«{{ event.tweet.tweet_text }}»</strong></a></span>
                <span class="tweet_date">{{ event.datetime|date:"d M H:i" }}</span>
            {% elif event.get_event_type_display == "подписка" %}
                <a href="{% url 'tweets' event.from_who.nickname %}"><img style="height: 30px; border-radius:5px; margin: 0px 5px -10px 5px;" src="{{ event.from_who.photo_url }}"/>
                <span class="tweet_text">{{ event.from_who.nickname }}</a> is now {{ event.event_type }}ing you </span>
                <span class="tweet_date">{{ event.datetime|date:"d M H:i" }}</span>
            {% elif event.get_event_type_display == "отписка" %}
                <a href="{% url 'tweets' event.from_who.nickname %}"><img style="height: 30px; border-radius:5px; margin: 0px 5px -10px 5px;" src="{{ event.from_who.photo_url }}"/>
                <span class="tweet_text">{{ event.from_who.nickname }}</a> isn't following you anymore </span>
                <span class="tweet_date">{{ event.datetime|date:"d M H:i" }}</span>
            {% endif %}
        </div>
        <br>
    {% endfor %}
{% endblock %}

twitter/templates/twitter/signup.html
<!DOCTYPE html>
{% load staticfiles %}


<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'twitter/style.css' %}" />
    <link rel="icon" type="image/png" href="http://www.favicon-generator.org/favicon-generator/htdocs/favicons/2015-11-05/d2638317c185659c4e458da1129d217e.ico"/>
    <meta charset="UTF-8">
    <title>Sign Up</title>
</head>
<body>
    <form method="post" action="{{request.path}}" enctype="multipart/form-data" id="signupform">
            {% csrf_token %}
            {{ form.as_p }}
            <p><input type="submit" value="Send"></p>
    </form>

    <h6 style="text-align:center; margin-top: 180px;"><a href="/">back to main</a></h6>
</body>
</html>

twitter/templates/twitter/testpage.html
<!DOCTYPE html>
{% load twitter_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>testpage</title>
</head>
<body>
    <p>hello #world again</p>
    <p>{{ text|tagify }}</p>
</body>
</html>